export const submittedSmartContracts = [
  {
    _id: "6-2023",
    submittedSmartContracts: 3,
    inuseSmartContracts: 3,
    sumAssetAmounts: 15,
    numberLockApiCalls: 160,
    numberUnlockApiCalls: 120,
  },
  {
    _id: "5-2023",
    submittedSmartContracts: 2,
    inuseSmartContracts: 1,
    sumAssetAmounts: 36,
    numberLockApiCalls: 500,
    numberUnlockApiCalls: 261,
  },
  {
    _id: "4-2023",
    submittedSmartContracts: 2,
    inuseSmartContracts: 2,
    sumAssetAmounts: 65,
    numberLockApiCalls: 522,
    numberUnlockApiCalls: 500,
  },
  {
    _id: "3-2023",
    submittedSmartContracts: 2,
    inuseSmartContracts: 1,
    sumAssetAmounts: 100,
    numberLockApiCalls: 5,
    numberUnlockApiCalls: 5,
  },
  {
    _id: "2-2023",
    submittedSmartContracts: 3,
    inuseSmartContracts: 2,
    sumAssetAmounts: 28,
    numberLockApiCalls: 150,
    numberUnlockApiCalls: 50,
  },
  {
    _id: "1-2023",
    submittedSmartContracts: 1,
    inuseSmartContracts: 1,
    sumAssetAmounts: 31,
    numberLockApiCalls: 5,
    numberUnlockApiCalls: 5,
  },
  {
    _id: "12-2022",
    submittedSmartContracts: 2,
    inuseSmartContracts: 0,
    sumAssetAmounts: 72,
    numberLockApiCalls: 25,
    numberUnlockApiCalls: 56,
  },
  {
    _id: "11-2022",
    submittedSmartContracts: 5,
    inuseSmartContracts: 1,
    sumAssetAmounts: 16,
    numberLockApiCalls: 5,
    numberUnlockApiCalls: 5,
  },
  {
    _id: "10-2022",
    submittedSmartContracts: 3,
    inuseSmartContracts: 2,
    sumAssetAmounts: 80,
    numberLockApiCalls: 445,
    numberUnlockApiCalls: 325,
  },
  {
    _id: "9-2022",
    submittedSmartContracts: 1,
    inuseSmartContracts: 0,
    sumAssetAmounts: 31,
    numberLockApiCalls: 5,
    numberUnlockApiCalls: 5,
  },
  {
    _id: "8-2022",
    submittedSmartContracts: 2,
    inuseSmartContracts: 1,
    sumAssetAmounts: 49,
    numberLockApiCalls: 536,
    numberUnlockApiCalls: 500,
  },
  {
    _id: "7-2022",
    submittedSmartContracts: 3,
    inuseSmartContracts: 2,
    sumAssetAmounts: 136,
    numberLockApiCalls: 514,
    numberUnlockApiCalls: 500,
  },
];
