From node:16.14.2 as build
ENV NODE_OPTIONS=--max_old_space_size=8192
WORKDIR /app
COPY ./ ./

RUN yarn install --prefer-offline
RUN yarn build-lib

RUN yarn build-cms

RUN yarn build-emp

RUN yarn build-jsk

FROM nginx as frontendimage

COPY --chown=nginx --from=build /app/cms/build /var/www/cms
COPY --chown=nginx --from=build /app/emp/build /var/www/emp
COPY --chown=nginx --from=build /app/jsk/build /var/www/jsk
